export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';

export const FETCH_BOOK_DETAIL = 'FETCH_BOOK_DETAIL';
export const FETCH_BOOK_DETAIL_SUCCESS = 'FETCH_BOOK_DETAIL_SUCCESS';
export const FETCH_BOOK_DETAIL_FAILURE = 'FETCH_BOOK_DETAIL_FAILURE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const GET_BORROW = 'GET_BORROW';
export const GET_BORROW_SUCCESS = 'GET_BORROW_SUCCESS';
export const GET_BORROW_FAILURE = 'GET_BORROW_FAILURE';

export const BORROW_BOOK = 'BORROW_BOOK';
export const BORROW_BOOK_SUCCESS = 'BORROW_BOOK_SUCCESS';
export const BORROW_BOOK_FAILURE = 'BORROW_BOOK_FAILURE';

export const RETURN_BOOK = 'RETURN_BOOK';
export const RETURN_BOOK_SUCCESS = 'RETURN_BOOK_SUCCESS';
export const RETURN_BOOK_FAILURE = 'RETURN_BOOK_FAILURE';
