export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';

export const FETCH_BOOK_DETAIL = 'FETCH_BOOK_DETAIL';
export const FETCH_BOOK_DETAIL_SUCCESS = 'FETCH_BOOK_DETAIL_SUCCESS';
export const FETCH_BOOK_DETAIL_FAILURE = 'FETCH_BOOK_DETAIL_FAILURE';
